# Generated by Django 2.2.2 on 2020-02-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('subject', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='dmt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dmt_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('dmt_id', models.IntegerField()),
                ('dmt_account_sid', models.CharField(max_length=100)),
                ('dmt_auth_token', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='dnt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dnt_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('dnt_account_sid', models.CharField(max_length=100)),
                ('dnt_auth_token', models.CharField(max_length=100)),
                ('dnt_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('pincode', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
